export const universalArgTypes = {
  as: { control: "text" },
  id: { control: "text" },
  role: { control: "text" },
  tabIndex: { control: "number" },
  title: { control: "text" },
  hidden: { control: "boolean" },
  draggable: { control: "boolean" },
  dir: { control: "select", options: ["ltr", "rtl", "auto"] },
  "aria-label": { control: "text", name: "aria-label" },
  "data-testid": { control: "text", name: "data-testid" },
  onClick: { action: "click" },
  onDoubleClick: { action: "doubleClick" },
  onFocus: { action: "focus" },
  onBlur: { action: "blur" },
  onKeyDown: { action: "keyDown" },
  onKeyUp: { action: "keyUp" },
  onMouseEnter: { action: "mouseEnter" },
  onMouseLeave: { action: "mouseLeave" },
  onPointerDown: { action: "pointerDown" },
  onPointerUp: { action: "pointerUp" },
  onTouchStart: { action: "touchStart" },
  onTouchEnd: { action: "touchEnd" },
  onChange: { action: "change" },
  onInput: { action: "input" },
  onSubmit: { action: "submit" },
  onWheel: { action: "wheel" },
  onDragStart: { action: "dragStart" },
  onDragEnd: { action: "dragEnd" },
};

export const styleSystemArgTypes = {
  m: { control: "text" },
  mx: { control: "text" },
  my: { control: "text" },
  mt: { control: "text" },
  mr: { control: "text" },
  mb: { control: "text" },
  ml: { control: "text" },
  p: { control: "text" },
  px: { control: "text" },
  py: { control: "text" },
  pt: { control: "text" },
  pr: { control: "text" },
  pb: { control: "text" },
  pl: { control: "text" },
  w: { control: "text" },
  h: { control: "text" },
  minW: { control: "text" },
  maxW: { control: "text" },
  minH: { control: "text" },
  maxH: { control: "text" },
  display: {
    control: "select",
    options: [
      "block",
      "inline",
      "inline-block",
      "flex",
      "grid",
      "inline-flex",
      "inline-grid",
      "contents",
      "none",
    ],
  },
  boxSizing: { control: "select", options: ["content-box", "border-box"] },
  overflow: {
    control: "select",
    options: ["visible", "hidden", "scroll", "auto", "clip"],
  },
  overflowX: {
    control: "select",
    options: ["visible", "hidden", "scroll", "auto", "clip"],
  },
  overflowY: {
    control: "select",
    options: ["visible", "hidden", "scroll", "auto", "clip"],
  },
  flex: { control: "text" },
  flexDir: {
    control: "select",
    options: ["row", "row-reverse", "column", "column-reverse"],
  },
  flexWrap: { control: "select", options: ["nowrap", "wrap", "wrap-reverse"] },
  justify: {
    control: "select",
    options: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
      "stretch",
    ],
  },
  align: {
    control: "select",
    options: ["stretch", "flex-start", "center", "flex-end", "baseline"],
  },
  alignSelf: {
    control: "select",
    options: [
      "auto",
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "baseline",
    ],
  },
  alignContent: {
    control: "select",
    options: [
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
    ],
  },
  gap: { control: "text" },
  rowGap: { control: "text" },
  columnGap: { control: "text" },
  flexGrow: { control: "number" },
  flexShrink: { control: "number" },
  flexBasis: { control: "text" },
  order: { control: "number" },
  gridCols: { control: "text" },
  gridRows: { control: "text" },
  gridAreas: { control: "text" },
  gridCol: { control: "text" },
  gridRow: { control: "text" },
  gridAutoFlow: { control: "text" },
  gridAutoCols: { control: "text" },
  gridAutoRows: { control: "text" },
  placeItems: { control: "text" },
  placeContent: { control: "text" },
  position: {
    control: "select",
    options: ["static", "relative", "absolute", "fixed", "sticky"],
  },
  top: { control: "text" },
  right: { control: "text" },
  bottom: { control: "text" },
  left: { control: "text" },
  inset: { control: "text" },
  zIndex: { control: "number" },
  fontFamily: { control: "text" },
  fontSize: { control: "text" },
  fontWeight: { control: "text" },
  lineHeight: { control: "text" },
  letterSpacing: { control: "text" },
  fontStyle: { control: "select", options: ["normal", "italic", "oblique"] },
  textAlign: {
    control: "select",
    options: ["left", "center", "right", "justify", "start", "end"],
  },
  textTransform: {
    control: "select",
    options: ["none", "capitalize", "uppercase", "lowercase"],
  },
  textDecoration: { control: "text" },
  textOverflow: { control: "text" },
  whiteSpace: {
    control: "select",
    options: [
      "normal",
      "nowrap",
      "pre",
      "pre-wrap",
      "pre-line",
      "break-spaces",
    ],
  },
  wordBreak: {
    control: "select",
    options: ["normal", "break-all", "keep-all", "break-word"],
  },
  overflowWrap: {
    control: "select",
    options: ["normal", "anywhere", "break-word"],
  },
  color: { control: "color" },
  opacity: { control: "text" },
  bg: { control: "text" },
  bgColor: { control: "color" },
  backgroundColor: { control: "color" },
  bgImage: { control: "text" },
  bgGradient: { control: "text" },
  bgClip: { control: "text" },
  bgPos: { control: "text" },
  bgSize: { control: "select", options: ["auto", "cover", "contain"] },
  bgRepeat: {
    control: "select",
    options: ["repeat", "repeat-x", "repeat-y", "no-repeat", "space", "round"],
  },
  bgAttachment: { control: "select", options: ["scroll", "fixed", "local"] },
  mixBlendMode: {
    control: "select",
    options: [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "difference",
      "exclusion",
      "hue",
      "saturation",
      "color",
      "luminosity",
    ],
  },
  border: { control: "text" },
  borderTop: { control: "text" },
  borderRight: { control: "text" },
  borderBottom: { control: "text" },
  borderLeft: { control: "text" },
  borderColor: { control: "color" },
  borderWidth: { control: "text" },
  borderStyle: {
    control: "select",
    options: [
      "none",
      "solid",
      "dashed",
      "dotted",
      "double",
      "groove",
      "ridge",
      "inset",
      "outset",
      "hidden",
    ],
  },
  rounded: { control: "text" },
  borderRadius: { control: "text" },
  outline: { control: "text" },
  outlineOffset: { control: "text" },
  boxShadow: { control: "text" },
  filter: { control: "text" },
  backdropFilter: { control: "text" },
  backdropBlur: { control: "text" },
  transform: { control: "text" },
  transformOrigin: { control: "text" },
  translateX: { control: "text" },
  translateY: { control: "text" },
  scale: { control: "text" },
  rotate: { control: "text" },
  skew: { control: "text" },
  cursor: {
    control: "select",
    options: [
      "default",
      "pointer",
      "text",
      "move",
      "not-allowed",
      "wait",
      "crosshair",
      "grab",
      "grabbing",
      "col-resize",
      "row-resize",
      "ns-resize",
      "ew-resize",
      "nesw-resize",
      "nwse-resize",
    ],
  },
  pointerEvents: { control: "select", options: ["auto", "none"] },
  userSelect: {
    control: "select",
    options: ["auto", "none", "text", "contain", "all"],
  },
  touchAction: {
    control: "select",
    options: [
      "auto",
      "none",
      "pan-x",
      "pan-y",
      "pan-left",
      "pan-right",
      "pan-up",
      "pan-down",
      "pinch-zoom",
      "manipulation",
    ],
  },
  objectFit: {
    control: "select",
    options: ["fill", "contain", "cover", "none", "scale-down"],
  },
  objectPosition: { control: "text" },
  aspectRatio: { control: "text" },
  visibility: { control: "select", options: ["visible", "hidden", "collapse"] },
  isolation: { control: "select", options: ["auto", "isolate"] },
  contain: {
    control: "select",
    options: ["none", "content", "strict", "size", "layout", "paint", "style"],
  },
  contentVisibility: {
    control: "select",
    options: ["visible", "auto", "hidden"],
  },
  scrollBehavior: { control: "select", options: ["auto", "smooth"] },
  scrollSnapType: { control: "text" },
  scrollSnapAlign: { control: "text" },
  scrollMargin: { control: "text" },
  scrollMarginTop: { control: "text" },
  scrollMarginRight: { control: "text" },
  scrollMarginBottom: { control: "text" },
  scrollMarginLeft: { control: "text" },
  scrollPadding: { control: "text" },
  scrollPaddingTop: { control: "text" },
  scrollPaddingRight: { control: "text" },
  scrollPaddingBottom: { control: "text" },
  scrollPaddingLeft: { control: "text" },
};

export const visualCommonArgTypes = {
  variant: { control: "select", options: ["solid", "outline", "ghost", "link"] },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
  radius: { control: "text" },
  elevation: { control: "select", options: [0, 1, 2, 3, 4, 5] },
  shadow: { control: "select", options: ["none", "sm", "md", "lg"] },
  tone: { control: "select", options: ["default", "subtle", "strong"] },
  colorScheme: { control: "text" },
  disabled: { control: "boolean" },
  loading: { control: "boolean" },
};

export const commonArgTypes = {
  ...universalArgTypes,
  ...styleSystemArgTypes,
  ...visualCommonArgTypes,
  customProps: { control: "object", description: "Extra attributes to spread onto the component root (e.g. {\"data-qa\":\"foo\"})" },
};
