import React, { Children, useRef, useState } from "react";
import { Badge } from "../components/Badge/Badge";

export default {
  id: "example-badge",
  title: "Badge Component",
  component: Badge,
  parameters: { layout: "centered" },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: "select",
      options: ["solid", "outline", "ghost", "link"],
    },
    size: { control: "select", options: ["xs", "sm", "md", "lg", "xl"] },
    color: {
      control: "select",
      options: ["neutral", "primary", "success", "warning", "error", "info"],
    },
    // tone removed; use style.opacity or --sb-opacity tokens
    radius: {
      control: "text",
      table: { type: { summary: "'none'|'sm'|'md'|'lg'|'full'|number" } },
    },
    elevation: { control: "number", min: 0, max: 5 },
    shadow: { control: "text" },
    as: { control: "text" },
    id: { control: "text" },
    tabIndex: { control: "number" },
    title: { control: "text" },
    hidden: { control: "boolean" },
    draggable: { control: "boolean" },
    dir: { control: "text" },
    lang: { control: "text" },
    "data-testid": { control: "text", name: "data-testid" },
    onClick: { action: "clicked" },
    onFocus: { action: "focus" },
    onBlur: { action: "blur" },
    onKeyDown: { action: "keydown" },
    onKeyUp: { action: "keyup" },
    // common shorthand style-system props to reveal in Show code
    m: { control: "text" },
    mx: { control: "text" },
    my: { control: "text" },
    mt: { control: "text" },
    mr: { control: "text" },
    mb: { control: "text" },
    ml: { control: "text" },
    p: { control: "text" },
    px: { control: "text" },
    py: { control: "text" },
    pt: { control: "text" },
    pr: { control: "text" },
    pb: { control: "text" },
    pl: { control: "text" },
    w: { control: "text" },
    h: { control: "text" },
  },
};

export const Primary = {
  name: "Badge",
  render: (args) => React.createElement(Badge, { ...args }),
  args: {
    id: "badge-1",
    className: "badge-story",
    label: "Active",
    variant: "solid",
    color: "success",
    size: "sm",
    radius: "md",
    elevation: 0,
    shadow: "none",
    dot: true,
    pill: true,
    tabIndex: 0,
    draggable: false,
    hidden: false,
    dir: "ltr",
    lang: "en",
    "data-testid": "badge",
    title: "Active",
    children: "Active",
    style: { fontWeight: "bold" },
    m: "0",
    px: "8px",
    py: "2px",
    w: "auto",
    h: "auto",
  },
};
